version: '3.4'

services:
  data-sim:    
    image: corynguyenfl/data-sim2
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: data-sim
    volumes:
      - .:/data-sim      
    environment:
      - APP_CONF=/data-sim/config/app.yaml
