nats:
  url: 'nats://192.168.86.39:4222'
microgrid-controller:
  enabled: false
  pcc:
    mrid: e6768784-48ad-40e9-af2a-9676413d4d6a
    W: 445.022
    is_closed: true  
  ess:
    mrid: 836a8638-b448-4961-8258-47aa18e05f65 
    reading_mrid: 6e595d68-67b4-434c-8c26-736104cc14fe 
    soc: 65.0 
    is_on: true
    mode: 2000 # valid mode: VSI_PQ: 2000, VSI_ISO: 2002   
  solar:
    mrid: 540b292a-e600-4ae4-b077-40b892ae6970 
    reading_mrid: 081a9cd4-b7d2-4a7c-b089-42d0053f8e6a         
    is_on: True
    W: 774.93
  generator:
    mrid: 8e202725-5a8d-45c2-b575-8161927c6770
    reading_mrid: 8e202725-5a8d-45c2-b575-8161927c6770
    is_on: false
    W: 152.323
  shop-meter:
    mrid: 0648ef71-cb63-4347-921a-9dbf178da687               
    W: 100.0      
  load-bank:    
    mrid: 4cadfaed-4176-453d-9625-e9ae8ad70529 
    reading_mrid: 2a09c597-d666-4354-a31a-dfe6da7727a9    
    is_on: false   
    W: 200.0
cvr:
  enabled: true
  recloser1:
    mrid: 9c9ca740-3032-4143-bf53-412e7e699f15 
    W: 445.022
    is_closed: true  
  recloser2:
    mrid: cd2d3c79-74c0-4d8d-a4ed-c710f0ceaf47 
    W: 445.022
    is_closed: true
  vr1:
    mrid: 82ad21e3-6f86-437b-a360-405ea3dca012
    pos: 1
    volLmHi: false
    volLmLo: false
    voltageSetPointEnabled: true
    source_primary_voltage: 123.0
    source_secondary_voltage: 123.0
    load_primary_voltage: 123.0
    load_secondary_voltage: 123.0
  vr2:
    mrid: 953ef053-c288-463a-a2ce-33c021ae61e9
    pos: 1
    volLmHi: false
    volLmLo: false
    voltageSetPointEnabled: true
    source_primary_voltage: 123.0
    source_secondary_voltage: 123.0
    load_primary_voltage: 123.0
    load_secondary_voltage: 123.0
  vr3:
    mrid: 9be8b771-7cd5-4335-95f8-165d0aff04fc
    pos: 1
    volLmHi: false
    volLmLo: false
    voltageSetPointEnabled: true
    source_primary_voltage: 123.0
    source_secondary_voltage: 123.0
    load_primary_voltage: 123.0
    load_secondary_voltage: 123.0
  capbank:
    mrid: ea6c74bd-2af3-450d-b459-b4bdf22371a3
    is_closed: false
    manual: true
    volLmt: false
    varLmt: false
    tempLmt: false
    Ia: 0.0
    Ib: 0.0
    Ic: 0.0
    Va: 0.0
    Vb: 0.0
    Vc: 0.0
    V2a: 0.0
    V2b: 0.0
    V3c: 0.0
    Wa: 0.0
    Wb: 0.0
    Wc: 0.0
  load1:
    mrid: f4be354c-cdde-4050-84de-2ec3c19f6d70
    Ia: 0.0
    Ib: 0.0
    Ic: 0.0
    Va: 0.0
    Vb: 0.0
    Vc: 0.0    
    Apparent: 0.0
    Reactive: 0.0
    W: 0.0    
  load2:
    mrid: 5c6a381b-ea49-4c12-84f5-93d5defa3394               
    Ia: 0.0
    Ib: 0.0
    Ic: 0.0
    Va: 0.0
    Vb: 0.0
    Vc: 0.0    
    Apparent: 0.0
    Reactive: 0.0
    W: 0.0
  load3:
    mrid: 5c6a381b-ea49-4c12-84f5-93d5defa3394               
    Ia: 0.0
    Ib: 0.0
    Ic: 0.0
    Va: 0.0
    Vb: 0.0
    Vc: 0.0    
    Apparent: 0.0
    Reactive: 0.0
    W: 0.0
  load4:
    mrid: 5c6a381b-ea49-4c12-84f5-93d5defa3394               
    Ia: 0.0
    Ib: 0.0
    Ic: 0.0
    Va: 0.0
    Vb: 0.0
    Vc: 0.0    
    Apparent: 0.0
    Reactive: 0.0
    W: 0.0
