nats:
    url: nats://192.168.86.39:4222
microgrid-controller:
    enabled: false
    pcc:
        mrid: e6768784-48ad-40e9-af2a-9676413d4d6a
        w: 0
        is_closed: true
    ess:
        mrid: 836a8638-b448-4961-8258-47aa18e05f65
        reading_mrid: 6e595d68-67b4-434c-8c26-736104cc14fe
        soc: 65
        mode: 2000
        is_on: true
        w: 0
    solar:
        mrid: 540b292a-e600-4ae4-b077-40b892ae6970
        is_on: true
        w: 0
    generator:
        mrid: 8e202725-5a8d-45c2-b575-8161927c6770
        reading_mrid: 8e202725-5a8d-45c2-b575-8161927c6770
        is_on: false
        w: 0
    shop-meter:
        mrid: 0648ef71-cb63-4347-921a-9dbf178da687
        w: 0
    load-bank:
        mrid: 4cadfaed-4176-453d-9625-e9ae8ad70529
        reading_mrid: 2a09c597-d666-4354-a31a-dfe6da7727a9
        is_on: false
        w: 0
cvr:
    enabled: true
    recloser1:
        mrid: 9c9ca740-3032-4143-bf53-412e7e699f15
        w: 0
        is_closed: false
    recloser2:
        mrid: cd2d3c79-74c0-4d8d-a4ed-c710f0ceaf47
        w: 0
        is_closed: true
    vr1:
        mrid: 82ad21e3-6f86-437b-a360-405ea3dca012
        pos: 1
        volLmHi: false
        volLmLo: false
        voltageSetPointEnabled: true
        source_primary_voltage: 123
        source_secondary_voltage: 123
        load_primary_voltage: 123
        load_secondary_voltage: 123
    vr2:
        mrid: 953ef053-c288-463a-a2ce-33c021ae61e9
        pos: -2
        volLmHi: false
        volLmLo: false
        voltageSetPointEnabled: true
        source_primary_voltage: 123
        source_secondary_voltage: 123
        load_primary_voltage: 123
        load_secondary_voltage: 123
    vr3:
        mrid: 9be8b771-7cd5-4335-95f8-165d0aff04fc
        pos: 1
        volLmHi: false
        volLmLo: false
        voltageSetPointEnabled: true
        source_primary_voltage: 123
        source_secondary_voltage: 123
        load_primary_voltage: 123
        load_secondary_voltage: 123
    capbank:
        mrid: ea6c74bd-2af3-450d-b459-b4bdf22371a3
        manual: true
        is_closed: false
        volLmt: false
        varLmt: false
        tempLmt: false
        ia: 0
        ib: 0
        ic: 0
        va: 0
        vb: 0
        vc: 0
        v2a: 0
        v2b: 0
        v2c: 0
        wa: 0
        wb: 0
        wc: 0
    load1:
        mrid: f4be354c-cdde-4050-84de-2ec3c19f6d70
        ia: 0
        ib: 0
        ic: 0
        va: 0
        vb: 0
        vc: 0
        apparent: 0
        reactive: 0
        w: 0
    load2:
        mrid: 5c6a381b-ea49-4c12-84f5-93d5defa3394
        ia: 0
        ib: 0
        ic: 0
        va: 0
        vb: 0
        vc: 0
        apparent: 0
        reactive: 0
        w: 0
    load3:
        mrid: 5c6a381b-ea49-4c12-84f5-93d5defa3394
        ia: 0
        ib: 0
        ic: 0
        va: 0
        vb: 0
        vc: 0
        apparent: 0
        reactive: 0
        w: 0
    load4:
        mrid: 5c6a381b-ea49-4c12-84f5-93d5defa3394
        ia: 0
        ib: 0
        ic: 0
        va: 0
        vb: 0
        vc: 0
        apparent: 0
        reactive: 0
        w: 0
